build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false

complexity:
  active: true
  LongMethod:
    active: true
    threshold: 120
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 8
  TooManyFunctions:
    active: false
  CyclomaticComplexMethod:
    active: true
    threshold: 20

style:
  active: true
  MagicNumber:
    active: false
  ReturnCount:
    active: true
    max: 4
  MaxLineLength:
    active: true
    maxLineLength: 140
  UnusedPrivateMember:
    active: true
  WildcardImport:
    active: false
  UnusedParameter:
    active: false

formatting:
  active: true
  android: true
  autoCorrect: true
  Indentation:
    active: true
    indentSize: 4
  MaximumLineLength:
    active: true
    maxLineLength: 140
  NoWildcardImports:
    active: false
  FunctionName:
    active: false
  FinalNewline:
    active: false
  NewLineAtEndOfFile:
    active: false
  ImportOrdering:
    active: false
  ArgumentListWrapping:
    active: false
  NoConsecutiveBlankLines:
    active: true
  Filename:
    active: false

naming:
  active: true
  FunctionNaming:
    active: true
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  MatchingDeclarationName:
    active: false

empty-blocks:
  active: true

potential-bugs:
  active: true

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false